# Mis parametros
PATH_ARENAS = 'arenas.csv'
PATH_EXCAVADORES = 'excavadores.csv'
PATH_CONSUMIBLES = 'consumibles.csv'
PATH_TESOROS = 'tesoros.csv'
PATH_PARTIDAS = "Partidas"
EXTENSION_PARTIDAS = ".txt"
ENCODING = "utf-8"
CARACTERES_INVALIDOS = '\/:*?"<>|'

VOLVER = '5'
SALIR = 'X'

PROB_ENCONTRAR_ITEM_MOJADA = 1
PROB_CONSUMIBLE_TESORO_MOJADA = 0.5
CONSUMIBLE = "consumible"
TESORO = "tesoro"
LISTA_ITEMS = [TESORO, CONSUMIBLE]
CALIDAD_EQUIPO = 1

ARENA_NORMAL = "normal"
ARENA_MOJADA = "mojada"
ARENA_ROCOSA = "rocosa"
ARENA_MAGNETICA = "magnetica"
LISTA_ARENAS = [ARENA_NORMAL, ARENA_MOJADA, ARENA_ROCOSA, ARENA_MAGNETICA]

EXCAVADOR_DOCENCIO = "docencio"
EXCAVADOR_TAREO = "tareo"
EXCAVADOR_HIBRIDO = "hibrido"

LLUVIA = "Lluvia"
TERREMOTO = "Terremoto"
DERRUMBE = "Derrumbe"

# Parametros torneo
DIAS_TOTALES_TORNEO = 100
ARENA_INICIAL = ARENA_NORMAL
CANTIDAD_EXCAVADORES_INICIALES = 5
METROS_META = 100

# Eventos
PROB_INICIAR_EVENTO = 0.3
PROB_LLUVIA = 0.5
PROB_TERREMOTO = 0.2
PROB_DERRUMBE = 0.3
METROS_PERDIDOS_DERRUMBE = 10

# Arena
POND_ARENA_NORMAL = 0.7

# Excavadores
FELICIDAD_PERDIDA = 5

PROB_ENCONTRAR_ITEM = 0.2
PROB_ENCONTRAR_TESORO = 0.4
PROB_ENCONTRAR_CONSUMIBLE = 0.6

FELICIDAD_ADICIONAL_DOCENCIO = 1
FUERZA_ADICIONAL_DOCENCIO = 1
ENERGIA_PERDIDA_DOCENCIO = 1

ENERGIA_ADICIONAL_TAREO = 1
SUERTE_ADICIONAL_TAREO = 1
EDAD_ADICIONAL_TAREO = 1
FELICIDAD_PERDIDA_TAREO = 1
