ANCHO_GRILLA = 11 # NO EDITAR
LARGO_GRILLA = 16 # NO EDITAR

# Complete con los demás parámetros
MIN_CARACTERES = 5
MAX_CARACTERES = 10

LUIGI_QUIETO = 'front'
TAMANO_CUADRICULA = 100

PATH_ELEMENTOS = 'sprites\Elementos'
PATH_FONDOS = 'sprites\Fondos'
PATH_PERSONAJES = 'sprites\Personajes'

NOMBRE_LUIGI = 'luigi'
CANTIDAD_VIDAS = 3

# Fantasmas
MIN_VELOCIDAD = 0.3
MAX_VELOCIDAD = 0.8
MAXIMO_FANTASMAS_VERTICAL = 2
MAXIMO_FANTASMAS_HORIZONTAL = 3
TIPO_HORIZONTAL = 'horizontal'
TIPO_VERTICAL = 'vertical'
DERECHA = 'derecha'
IZQUIERDA = 'izquierda'
DIRECCIONES_FANTASMA = [TAMANO_CUADRICULA, -TAMANO_CUADRICULA]
ARRIBA = 'arriba'
ABAJO = 'abajo'

# Constructor
MAPA_LUIGI = 'L'
MAPA_PARED = 'P'
MAPA_FUEGO = 'F'
MAPA_FANTASMA_H = 'H'
MAPA_FANTASMA_V = 'V'
MAPA_ESTRELLA = 'S'
MAPA_ROCA = 'R'