ANCHO_GRILLA = 11 # NO EDITAR
LARGO_GRILLA = 16 # NO EDITAR

# Complete con los demás parámetros
TAMANO_GRILLA = 50
ANCHO_MAPA = ANCHO_GRILLA - 2
LARGO_MAPA = LARGO_GRILLA - 2
TIEMPO_JUEGO = 110

MIN_CARACTERES = 5
MAX_CARACTERES = 10

LUIGI_QUIETO = 'front'

PATH_FONDOS = 'sprites\Fondos'
PATH_ELEMENTOS = 'sprites/Elementos/'
PATH_ENTIDADES = 'sprites/Personajes/'

NOMBRE_LUIGI = 'luigi'
CANTIDAD_VIDAS = 3


# Fantasmas
MIN_VELOCIDAD = 0.3
MAX_VELOCIDAD = 0.8
MAXIMO_FANTASMAS_VERTICAL = 2
MAXIMO_FANTASMAS_HORIZONTAL = 3
TIPO_HORIZONTAL = 'white'
TIPO_VERTICAL = 'red'
DERECHA = 'rigth'
IZQUIERDA = 'left'
VERTICAL = 'vertical'
NOMBRES_DIRECCIONES_FANTASMA = {TIPO_HORIZONTAL: [DERECHA, IZQUIERDA], TIPO_VERTICAL: [VERTICAL]}
DIRECCIONES_FANTASMA = {DERECHA: [TAMANO_GRILLA], IZQUIERDA: [-TAMANO_GRILLA], VERTICAL: [TAMANO_GRILLA, -TAMANO_GRILLA]}
ARRIBA = 'arriba'
ABAJO = 'abajo'

# Constructor
MAPA_BORDE = 'B'
MAPA_LUIGI = 'L'
MAPA_PARED = 'P'
MAPA_FUEGO = 'F'
MAPA_FANTASMA_H = 'H'
MAPA_FANTASMA_V = 'V'
MAPA_ESTRELLA = 'S'
MAPA_ROCA = 'R'

SPRITES_ELEMENTOS = {MAPA_BORDE: PATH_ELEMENTOS + 'bordermap.png',
                     MAPA_FUEGO: PATH_ELEMENTOS + 'fire.png',
                     MAPA_ESTRELLA: PATH_ELEMENTOS + 'osstar.png',
                     MAPA_ROCA: PATH_ELEMENTOS + 'rock.png',
                     MAPA_PARED: PATH_ELEMENTOS + 'wall.png'}
SPRITES_ENTIDADES = {
    MAPA_LUIGI: PATH_ENTIDADES + 'luigi_front.png',
    MAPA_FANTASMA_H: PATH_ENTIDADES + 'white_ghost_rigth_1.png',
    MAPA_FANTASMA_V: PATH_ENTIDADES + 'red_ghost_vertical_1.png',
}
FILTRO_TODOS = 'Todos'
FILTROS = {FILTRO_TODOS: SPRITES_ENTIDADES | SPRITES_ELEMENTOS, 'Bloques': SPRITES_ELEMENTOS, 'Entidades': SPRITES_ENTIDADES}
